#!/bin/bash -v

mvn clean package -Dtargetbinary=transmitter
cp -v target/markoff-1.0-SNAPSHOT.jar transmitter.jar

mvn clean package -Dtargetbinary=receiver
cp -v target/markoff-1.0-SNAPSHOT.jar receiver.jar





